### ISSUE TITLE
permissions issue on files

### ISSUE THREAD

**Issue by continuata** [Niquolas/unrar-binaries#1]
this is a great library ... solves a massive headache for me.

But ... I need to go in manually and `chmod u+x ...` on the unrar executable, is there any way to do this in a post-install step for all the platforms?

**Comment by Niquolas** [comment]
Thanks for the issue, does 03fa475 look like a suitable solution?

**Comment by continuata** [comment]
testing now

**Comment by continuata** [comment]
I'm a bit confused ... the latest version I pulled on npm a few days ago was v1.0.2 ... but the latest on master is v1.0.1 ... what happened to v1.0.2?

**Comment by continuata** [comment]
that branch seems to work for me.

**Comment by Niquolas** [comment]
I was just as confused as you are, so I checked the two packages and 1.0.2 was just to update some errors in the README.md. Not sure why the version change didn't end up on master though.

Anyway, I'll merge the branch and publish a new version. Thanks for the help!
